### ISSUE TITLE
calc of mAP

### ISSUE THREAD

**Issue by wangzhexiaoyu** [thulab/DeepHash#30]
![屏幕快照 2019-05-22 下午12 29 41](https://user-images.githubusercontent.com/48741174/58147519-749a1a00-7c8d-11e9-89ff-64ae9cd1ec06.png)
the last two lines shows that query with no correct return will not be included in APx, is it a bug here? Thanks!

**Comment by bl0** [comment]
Hi, this is not a bug. If no relevant results are retrieved, the MAP is not well defined and should not be included in the APx. 
You can also simply set it to 0, but it doesn't have an obvious impact on the result since it's unlikely for our method to find 0 relevant code in the database similar to a query.

**Comment by wangzhexiaoyu** [comment]
OK, thank you
